# Define utils data
metadata_options = [
    {"label": "Language Score", "value": "language_score"},
    {"label": "Number of Words", "value": "num_words"},
    {"label": "Number of Tokens", "value": "num_tokens"},
    {"label": "Number of Characters", "value": "num_chars"},
    {"label": "Number of Emails", "value": "num_emails"},
    {"label": "Number of Paragraphs", "value": "num_paras"},
    {"label": "Average length (paragraph)", "value": "avg_para_len"},
    {"label": "Average length (words)", "value": "avg_word_len"},
    {"label": "Percentage of Stopwords", "value": "pct_stopwords"},
    {"label": "TTR Tokens", "value": "ttr_tokens"},
    {"label": "TTR Tokens (lowercase)", "value": "ttr_tokens_lower"},
    {"label": "TTR Words", "value": "ttr_words"},
    {"label": "TTR Words (lowercase)", "value": "ttr_words_lower"},
    {"label": "Perplexity", "value": "perplexity"},
    {"label": "Perentage of Space", "value": "pct_space"},
    {"label": "Perentage of Lower", "value": "pct_lower"},
    {"label": "Perentage of Upper", "value": "pct_upper"},
    {"label": "Perentage of Title", "value": "pct_title"},
    {"label": "Perentage of Mixed", "value": "pct_mixed"},
    {"label": "Perentage of Punctuation", "value": "pct_puncts"},
    {"label": "Perentage of Words", "value": "pct_words"},
    {"label": "Percentage of Numbers", "value": "pct_numbers"},
    {"label": "Percentage of Others", "value": "pct_others"},
]
